
ClassStrategyCO = {};
ClassStrategyNC = {};

function InitializeStrategy()
	ClassStrategyCO = {
[1] = {"grind","Autonomous Activity","The bot will search for targets within its field of view and attack them when it has no target during combat."},
[2] = {"attack weak","Free Attack","The bot will freely select targets to attack during combat."},
[3] = {"attack force","Passive Attack","The bot will not select targets on its own; you must manually assign the attack target."},
[4] = {"tank","Single Target Tank","The bot only tanks one monster at a time, moving to the next after it dies."},
[5] = {"tank aoe","Multi-Target Tank","The bot will tank all monsters involved in the combat."},
[6] = {"tank assist","Tank Assist","The bot assists by attacking the current target of the group's tank character."},
[7] = {"dps","Single Target DPS","The bot only attacks one monster at a time, moving to the next after it dies."},
[8] = {"dps aoe","AoE DPS","The bot will use AoE skills when there are many monsters in combat."},
[9] = {"dps assist","DPS Assist","The bot assists the group by dealing damage to the monsters."},
[10] = {"dps debuff","Damaging BUFF","The bot will apply Damage-over-Time (DoT) buffs to the target during combat."},
[11] = {"heal","Heal Teammates","The bot will heal injured teammates during combat and stop dealing DPS."},
[12] = {"aoe","Area of Effect Attack","The bot will use area-of-effect damaging skills during combat."},
[13] = {"flee","Maintain Distance","The bot will try to run away if it is approached by its current melee target during combat."},
[14] = {"fire","Fire Spells","The bot uses Fire spells to damage targets during combat. (For Mage bots)"},
[15] = {"fire aoe","Fire AoE","The bot uses Fire AoE spells when there are many monsters in combat. (For Mage bots)"},
[16] = {"frost","Frost Spells","The bot uses Frost spells to damage targets during combat. (For Mage bots)"},
[17] = {"frost aoe","Frost AoE","The bot uses Frost AoE spells when there are many monsters in combat. (For Mage bots)"},
[18] = {"arcane","Arcane Spells","The bot uses Arcane spells to damage targets during combat. (For Mage bots)"},
[19] = {"threat","Threat Control","The bot will throttle its damage output conservatively during combat to prevent pulling aggro (OT)."},
[20] = {"conserve mana","Mana Control","The bot will conserve its mana during combat, lowering its overall damage output."},
[21] = {"shadow","Shadow Spells","The bot uses Shadow spells to damage targets during combat. (For Warlock and Priest bots)"},
[22] = {"shadow aoe","Shadow AoE","The bot uses Shadow AoE spells when there are many monsters in combat. (For Warlock and Priest bots)"},
[23] = {"shadow debuff","Shadow Damage BUFF","The bot will apply Shadow Damage-over-Time (DoT) buffs to the target during combat. (For Warlock and Priest bots)"},
[24] = {"melee","Melee Combat","The bot always stays close to the target to attack during combat. (For Shaman bots)"},
[25] = {"melee aoe","Melee AoE","The bot stays close to targets to perform area attacks during combat. (For Shaman bots)"},
[26] = {"rshadow","Shadow Resistance Aura","The bot activates Shadow Resistance Aura during combat. (For Paladin bots)"},
[27] = {"rfrost","Frost Resistance Aura","The bot activates Frost Resistance Aura during combat. (For Paladin bots)"},
[28] = {"rfire","Fire Resistance Aura","The bot activates Fire Resistance Aura during combat. (For Paladin bots)"},
[29] = {"barmor","Armor Defense Aura","The bot activates Devotion/Armor Aura during combat. (For Paladin bots)"},
[30] = {"bspeed","Mount Speed Aura","The bot activates Crusader/Mount Speed Aura during combat. (For Paladin bots)"},
[31] = {"rnature","Nature Resistance Aura","The bot activates Nature Resistance Aspect/Aura during combat. (For Hunter bots)"},
[32] = {"bhealth","Health BUFF","The bot casts health-increasing buffs on itself and teammates during combat."},
[33] = {"bmana","Utility BUFF","The bot casts utility/mana buffs on itself and teammates during combat."},
[34] = {"bdps","Offensive BUFF","The bot casts offensive/damage buffs on itself and teammates during combat."},
[35] = {"bear","Bear and Dire Bear Form","The bot transforms into a Bear to tank/DPS during combat. (For Druid bots)"},
[36] = {"cat","Cat Form","The bot transforms into a Cat to deal DPS during combat. (For Druid bots)"},
[37] = {"cat aoe","Cat AoE","The bot transforms into a Cat to perform area attacks during combat. (For Druid bots)"},
[38] = {"caster","Ranged Spell DPS","The bot uses ranged spells to deal damage during combat. (For Druid and Shaman bots)"},
[39] = {"caster aoe","Ranged AoE Spells","The bot uses ranged AoE spells when there are many monsters in combat. (For Druid and Shaman bots)"},
[40] = {"caster debuff","Ranged Damage BUFF","The bot applies ranged Damage-over-Time (DoT) buffs to the target during combat. (For Druid and Shaman bots)"},
[41] = {"totems","Totems","The bot drops totems around itself during combat. (For Shaman bots)"},
[42] = {"loot","Loot","The bot will loot nearby corpses during combat."},
[43] = {"naxx","Naxxramas","The bot's behavior will be optimized for the Naxxramas raid. (Only effective inside Naxxramas)"},
	};

	ClassStrategyNC = {
[1] = {"grind","Autonomous Activity","When out of combat, the bot will search for targets within its field of view and attack them."},
[2] = {"move random","Random Movement","When out of combat, the bot will run around randomly if it gets bored."},
[3] = {"attack weak","Free Attack","When out of combat, the bot will freely select a target to attack the moment combat is initiated."},
[4] = {"attack force","Passive Attack","When out of combat, the bot will not initiate any attacks; you must manually assign the attack target."},
[5] = {"bhealth","Health BUFF","When out of combat, the bot casts health-increasing buffs on itself and teammates."},
[6] = {"bmana","Utility BUFF","When out of combat, the bot casts utility/mana buffs on itself and teammates."},
[7] = {"bdps","Offensive BUFF","When out of combat, the bot casts offensive/damage buffs on itself and teammates."},
[8] = {"emote","Emote","When out of combat, the bot will occasionally perform emotes if it gets bored."},
[9] = {"food","Resting","After leaving combat, the bot will drink water and eat food depending on its resource status."},
[10] = {"loot","Loot","After leaving combat, the bot will loot nearby corpses."},
[11] = {"stay","Stay","When out of combat, the bot stands still on the spot and does not move."},
[12] = {"follow","Follow","When out of combat, the bot follows the player's movements."},
[13] = {"quest","Quest","When out of combat, the bot will accept and complete quests with the NPC the player is currently interacting with."},
[14] = {"naxx","Naxxramas","The bot's behavior will be optimized for the Naxxramas raid. (Only effective inside Naxxramas)"},

	};
end
